// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  form_box: dynamic(() => import("./FormBox")),
  hero: dynamic(() => import("./Hero")),
  hero_pricing: dynamic(() => import("./HeroPricing")),
  image_block: dynamic(() => import("./ImageBlock")),
  link_project: dynamic(() => import("./LinkProject")),
  new_hero: dynamic(() => import("./NewHero")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
};
